### ISSUE TITLE
Cannot install (IMPORT FAILED)

### ISSUE THREAD

**Issue by Musigreg** [SeargeDP/ComfyUI_Searge_LLM#23]
At first, I had an issue very similar to https://github.com/SeargeDP/ComfyUI_Searge_LLM/issues/3 (Last post)

Then I downloaded the llama.dll from another website and replace the original one: No error message anymore.
But even though the error message is gone, I still have "IMPORT FAILED" when trying to use it.

Here is the log: 

Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Searge_LLM\__init__.py", line 1, in <module>
    from .Searge_LLM_Node import *
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Searge_LLM\Searge_LLM_Node.py", line 13, in <module>
    Llama = importlib.import_module("llama_cpp_cuda").Llama
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp_cuda\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 1315, in <module>
    @ctypes_function("llama_n_ubatch", [llama_context_p_ctypes], ctypes.c_uint32)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 126, in decorator
    func = getattr(lib, name)
           ^^^^^^^^^^^^^^^^^^
  File "ctypes\__init__.py", line 389, in __getattr__
  File "ctypes\__init__.py", line 394, in __getitem__
AttributeError: function 'llama_n_ubatch' not found

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Searge_LLM module for custom nodes: function 'llama_n_ubatch' not found
Initializing ControlAltAI Nodes

Thanks in advance.

**Comment by ffdown** [comment]
When loading the graph, the following node types were not found

Searge_AdvOptionsNode
Searge_LLM_Node

**Comment by ffdown** [comment]
`Traceback (most recent call last):
  File "X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 75, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ctypes\__init__.py", line 376, in __init__
OSError: [WinError 127] Не найдена указанная процедура

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Searge_LLM\__init__.py", line 1, in <module>
    from .Searge_LLM_Node import *
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Searge_LLM\Searge_LLM_Node.py", line 13, in <module>
    Llama = importlib.import_module("llama_cpp_cuda").Llama
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp_cuda\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 88, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 77, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library 'X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp_cuda\lib\llama.dll': [WinError 127] Не найдена указанная процедура

Cannot import X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Searge_LLM module for custom nodes: Failed to load shared library 'X:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp_cuda\lib\llama.dll': [WinError 127] Не найдена указанная процедура`

**Comment by kikeelrojo** [comment]
same issue here, but in Mac. It doesn't load as it fails to install correctly. When opening comfyui it says:
ModuleNotFoundError: No module named 'llama_cpp'

tried to install llama trough terminal but always get:
*** CMake build failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama_cpp_python
Failed to build llama_cpp_python
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (llama_cpp_python)

**Comment by bitsentinel-cell** [comment]
> When loading the graph, the following node types were not found
> 
> Searge_AdvOptionsNode Searge_LLM_Node

same here

**Comment by BastionNtB** [comment]
I'm getting the same errors.

```
Traceback (most recent call last):
  File "/root/ComfyUI/custom_nodes/ComfyUI_Searge_LLM/Searge_LLM_Node.py", line 13, in <module>
    Llama = importlib.import_module("llama_cpp_cuda").Llama
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'llama_cpp_cuda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ComfyUI/nodes.py", line 2113, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/ComfyUI/custom_nodes/ComfyUI_Searge_LLM/__init__.py", line 1, in <module>
    from .Searge_LLM_Node import *
  File "/root/ComfyUI/custom_nodes/ComfyUI_Searge_LLM/Searge_LLM_Node.py", line 15, in <module>
    Llama = importlib.import_module("llama_cpp").Llama
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'llama_cpp'
```

**Comment by Renz1998** [comment]
still error

**Comment by Musigreg** [comment]
> still error

Yeah... I just abandonned it... It's not gonna be fixed...

**Comment by IckeBins67** [comment]
so many users can't use this node and still unfixed, can't understand.
