### ISSUE TITLE
llama.cpp Issue with Normal ComfyUI Installation.

### ISSUE THREAD

**Issue by ialhabbal** [SeargeDP/ComfyUI_Searge_LLM#3]
My ComfyUI is not the portable. I installed the Searge LLM with the ComfyUI manager, I got the Traceback below error. I tried to Install the following commands inside the VENV after activating it but I got an error saying these were not compatible with the platform. My python 3.10.6, and my CUDA is 11.8.

python -m pip install https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases/download/cpu/llama_cpp_python-0.2.89+cpuavx2-cp311-cp311-win_amd64.whl
python -m pip install https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.2.89+cu121-cp311-cp311-win_amd64.whl

Traceback (most recent call last):
  File "L:\ComfyUI\venv\lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 75, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)  # type: ignore
  File "C:\Users\ialhabbal\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'L:\ComfyUI\venv\lib\site-packages\llama_cpp_cuda\lib\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "L:\ComfyUI\custom_nodes\ComfyUI_Searge_LLM\__init__.py", line 1, in <module>
    from .Searge_LLM_Node import *
  File "L:\ComfyUI\custom_nodes\ComfyUI_Searge_LLM\Searge_LLM_Node.py", line 13, in <module>
    Llama = importlib.import_module("llama_cpp_cuda").Llama
  File "C:\Users\ialhabbal\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "L:\ComfyUI\venv\lib\site-packages\llama_cpp_cuda\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "L:\ComfyUI\venv\lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 88, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "L:\ComfyUI\venv\lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 77, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library 'L:\ComfyUI\venv\lib\site-packages\llama_cpp_cuda\lib\llama.dll': Could not find module 'L:\ComfyUI\venv\lib\site-packages\llama_cpp_cuda\lib\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

Cannot import L:\ComfyUI\custom_nodes\ComfyUI_Searge_LLM module for custom nodes: Failed to load shared library 'L:\ComfyUI\venv\lib\site-packages\llama_cpp_cuda\lib\llama.dll': Could not find module 'L:\ComfyUI\venv\lib\site-packages\llama_cpp_cuda\lib\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by SeargeDP** [comment]
Can you try installing llama-cpp manually in your python environment? The command `python -m pip install llama-cpp-python` should work. If any version of llama-cpp is already in your python environment, you may have to uninstall it first.

To check if llama-cpp is already installed use `python -m pip list` and check if it's listed in the output. If you see for example `llama_cpp_python` and `llama_cpp_python_cuda` listed, you could use `python -m pip uninstall llama_cpp_python` and `python -m pip uninstall llama_cpp_python_cuda`. After that you can install llama-cpp manually with the command I list at the top of this post.

**Comment by jmorbit** [comment]
I had the same issue:

> Can you try installing llama-cpp manually in your python environment? The command `python -m pip install llama-cpp-python` should work. If any version of llama-cpp is already in your python environment, you may have to uninstall it first.
> 
> To check if llama-cpp is already installed use `python -m pip list` and check if it's listed in the output. If you see for example `llama_cpp_python` and `llama_cpp_python_cuda` listed, you could use `python -m pip uninstall llama_cpp_python` and `python -m pip uninstall llama_cpp_python_cuda`. After that you can install llama-cpp manually with the command I list at the top of this post.

Your suggestion fixed the problem!

**Comment by Jmagick2033** [comment]
Your solution works but, it leaves me waiting on the CPU to run the model. Is there a fix for running the GPU. I have a RTX3060 12GB which would be faster. I have even tried with a new install of ComfyUI to no avail. The original error is posted below.

Error occurred when executing Searge_LLM_Node:

[WinError -1073741795] Windows Error 0xc000001d

  File "H:\apps\ComfyUI-for-testing\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\apps\ComfyUI-for-testing\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\apps\ComfyUI-for-testing\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\apps\ComfyUI-for-testing\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\apps\ComfyUI-for-testing\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Searge_LLM\Searge_LLM_Node.py", line 67, in main
    model_to_use = Llama(
                   ^^^^^^
  File "H:\apps\ComfyUI-for-testing\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp_cuda\llama.py", line 207, in __init__
    llama_cpp.llama_backend_init()

**Comment by SeargeDP** [comment]
That looks like a potential gpu driver issue to me. 

You can manually install llama-cpp, but make sure it is compiled with cuda support if you are installing it manually. Google can help with information about how to do that. By default I have specified a pre-compiled version of llama-cpp with cuda support in the requirements.txt file.

**Comment by ialhabbal** [comment]
This custom node is specifically built for Python 3.11 and will not work with 3.10.

**Comment by vihangasa14** [comment]
![Screenshot 2024-09-05 101452](https://github.com/user-attachments/assets/fce2bfe1-8b75-48c3-a8a5-e816634e7c02)
PS G:\SD AI\UI\Comfyui\ComfyUI> pip install llama-cpp-python
Collecting llama-cpp-python
  Using cached llama_cpp_python-0.2.90.tar.gz (63.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\vihanga\appdata\local\programs\python\python311\lib\site-packages (from llama-cpp-python) (4.9.0)
Requirement already satisfied: numpy>=1.20.0 in c:\users\vihanga\appdata\local\programs\python\python311\lib\site-packages (from llama-cpp-python) (1.26.3)
Requirement already satisfied: diskcache>=5.6.1 in c:\users\vihanga\appdata\local\programs\python\python311\lib\site-packages (from llama-cpp-python) (5.6.3)
Requirement already satisfied: jinja2>=2.11.3 in c:\users\vihanga\appdata\local\programs\python\python311\lib\site-packages (from llama-cpp-python) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vihanga\appdata\local\programs\python\python311\lib\site-packages (from jinja2>=2.11.3->llama-cpp-python) (2.1.5)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      *** scikit-build-core 0.10.5 using CMake 3.30.2 (wheel)
      *** Configuring CMake...
      2024-09-05 09:56:33,366 - scikit_build_core - WARNING - Can't find a Python library, got libdir=None, ldlibrary=None, multiarch=None, masd=None
      loading initial cache file C:\Users\Vihanga\AppData\Local\Temp\tmp5odzna7x\build\CMakeInit.txt
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:3 (project):
        Running

         'nmake' '-?'

        failed with:

         no such file or directory


      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (llama-cpp-python)

Traceback (most recent call last):
  File "G:\SD AI\UI\Comfyui\python_embeded\Lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 75, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ctypes\__init__.py", line 376, in __init__
OSError: [WinError 127] The specified procedure could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\SD AI\UI\Comfyui\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\SD AI\UI\Comfyui\ComfyUI\custom_nodes\ComfyUI_Searge_LLM\__init__.py", line 1, in <module>
    from .Searge_LLM_Node import *
  File "G:\SD AI\UI\Comfyui\ComfyUI\custom_nodes\ComfyUI_Searge_LLM\Searge_LLM_Node.py", line 13, in <module>
    Llama = importlib.import_module("llama_cpp_cuda").Llama
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "G:\SD AI\UI\Comfyui\python_embeded\Lib\site-packages\llama_cpp_cuda\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "G:\SD AI\UI\Comfyui\python_embeded\Lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 88, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\SD AI\UI\Comfyui\python_embeded\Lib\site-packages\llama_cpp_cuda\llama_cpp.py", line 77, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library 'G:\SD AI\UI\Comfyui\python_embeded\Lib\site-packages\llama_cpp_cuda\lib\llama.dll': [WinError 127] The specified procedure could not be found

Cannot import G:\SD AI\UI\Comfyui\ComfyUI\custom_nodes\ComfyUI_Searge_LLM module for custom nodes: Failed to load shared library 'G:\SD AI\UI\Comfyui\python_embeded\Lib\site-packages\llama_cpp_cuda\lib\llama.dll': [WinError 127] The specified procedure could not be found
